# Hand-written messages in styles NOT produced by the generator (never used for training).
OOD=[
("Sir aapke liye special offer hai. Sirf 3 din me 2 lakh ko 6 lakh banaye. Hamare analyst ne 100% accurate calls diye hai. Abhi contact karo 98XXXXXX12",1),
("Hello, I am Rahul from Alpha Capital. We manage HNI portfolios and guarantee 4% weekly. Minimum deposit 50k. Add me to our private group for proof of withdrawals.",1),
("Dear customer your demat account will be blocked today. Update PAN immediately at http://hdfcsec-kyc.top/verify to avoid penalty.",1),
("आप चुने गए हैं! फ्री ट्रेनिंग के बाद हर दिन 5000 रुपये कमाएँ। नीचे लिंक से ऐप डाउनलोड कर के रजिस्टर करें।",1),
("Brother, big operator is accumulating this smallcap, target 3x next week. Buy before announcement. Forward only to trusted friends.",1),
("Congrats your IPO allotment is confirmed for ABC Ltd at grey market price. Pay token amount to my account to hold the shares.",1),
("Our SEBI approved algo gives 30% monthly, no loss ever. Join today, 40 members only. Telegram: @algoking_official",1),
("Madam aapka refund pending hai SEBI se. Processing charge 1500 Gpay karein, aur screen share karne ke liye anydesk download karein.",1),
("Mutual fund se 10 guna paisa banao. Hamara plan join karo, daily profit seedha bank me, no risk. WhatsApp me 'JOIN' likho.",1),
("FREE stock market course!! Learn from experts and get 3 sure shot tips daily. Only for the first 100 students. Click here bit.ly/freeprofit",1),
("Urgent: Your Upstox account is suspended. Verify now at upstox-secure.in and enter the OTP to reactivate.",1),
("Invest in our crypto-stock scheme, money doubles in 15 days. Thousands already earned. SEBI registered no. pending but safe.",1),
("Bhaiya ye wala stock kal upper circuit lagega, insider news hai. Aaj hi lelo aur kisi ko mat batana.",1),
("निवेश करें और हर हफ्ते 25% ब्याज पाएं। गारंटी हमारी। पहले 5000 रजिस्ट्रेशन फीस इस नंबर पर फोन-पे करें।",1),
("Special NRI offer: guaranteed 18% annual return on foreign portfolio investment, no tax, no paperwork. Transfer to our private account.",1),
("Your SIP instalment of Rs 3,000 for Parag Parikh Flexi Cap is due on 7 Nov. Ensure funds in your account. Mutual fund investments are subject to market risks.",0),
("Thanks for visiting our branch today. Your demat account opening request is received. Documents will be verified within 7 working days.",0),
("आपके डीमैट खाते में नॉमिनी जोड़ने की अंतिम तिथि 31 दिसंबर है। कृपया अपने डीपी की वेबसाइट पर जाकर पूरा करें।",0),
("Dad, I checked the mutual fund app. The statement shows 12% growth this year. Not guaranteed of course, but looks fine.",0),
("OTP for logging in to your trading account is 482913. Never share this code with anyone, including our staff.",0),
("SEBI reminds investors: do not trust unsolicited tips on social media or any group promising assured returns. Check registration on the SEBI portal.",0),
("Your order to buy 10 shares has been executed. Contract note will be sent by email. Brokerage charges as per your plan.",0),
("आज शाम 6 बजे निवेशक जागरूकता वेबिनार है, विषय: फर्जी निवेश स्कीम से कैसे बचें। रजिस्ट्रेशन मुफ्त है।",0),
("Dividend of Rs 2.50 per share has been credited to your bank account ending 4521 for holdings as on record date.",0),
("Aaj office me late ho jaunga, tum SIP ka reminder dekh lena aur khate me paise rakhna.",0),
("New fund offer opens on 10 Nov. Please read the scheme information document carefully before investing. Past performance may not be sustained.",0),
("Your KYC is verified successfully. No further action is required. Thank you for choosing us.",0),
("Mom, bank ne bola FD ka rate 7.1% hai. Wo guaranteed return wala hota hai kyunki bank deposit hai, par tax lagega.",0),
("Statement for September is ready. Open the official app to download. We never ask for your password or PIN over call or message.",0),
("Reminder: The market holiday is on Diwali Muhurat day. Trading will be open only for one hour in the evening.",0),
("Alert: A login from a new device was detected on your account. If this was not you, change password in the app and call the number on our website.",0)]
